name: Deploy to Simply.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
    
    - name: Configure SSH
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa 
        cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pem
        ssh-keyscan <server-address> >> ~/.ssh/known_hosts
    
    - name: Deploy to Simply.com
      run: |
        sshpass -p zpmt5dhg -i ~/.ssh/id_rsa.pem danishxboxleagu.dk@linux279.unoeuro.com 'cd /staging/wp-content/plugins/dxl-api && git pull'