name: Deploy to Simply.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GitHub SSH
      uses: MrSquaare/ssh-setup-action@v2
      with:
        host: linux279.unoeuro.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
    
    - name: Deploy to Simply.com
      run: |  
        cd staging/wp-content/plugins/dxl-api && git pull