name: Deploy to Simply.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
    
    - name: Deploy to Simply.com
      run: |
        
        echo ${{ secrets.SSH_PRIVATE_KEY }} > ./id_rsa.pem 
        chmod 600 ./id_rsa
        sshpass -p ${{ secrets.SSH_PASSWORD }} sshpass zpmt5dhg ssh -i ./id_rsa.pem danishxboxleagu.dk@linux279.unoeuro.com 'cd staging/wp-content/plugins/dxl-api && git pull'