name: DXL API deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan linux279.unoeuro.com >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh -i ./id_rsa.pem danishxboxleagu.dk@linux279.unoeuro.com 'cd /staging/wp-content/plugins/dxl-api && git pull'
