name: Deploy to Simply.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
    
    - name: Deploy to Simply.com
      run: |
        mkdir .ssh && cd .ssh && touch id_rsa && echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa && chmod 600 id_rsa && sshpass -p zpmt5dhg ssh -i id_rsa danishxboxleagu.dk@linux279.unoeuro.com
