name: Deploy to Simply.com

on:
  push:
    branches: [master, staging]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Creating pull request
          run: echo "Creating pull request for staging branch"
        
        - name: Pull request staging - master
          uses: Poorva17/create-pr-action@v2.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            HEAD_BRANCH: staging
            BASE_BRANCH: master
            PR_TITLE: "staging - master: ${{ github.event.head_commit.message }}"
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass

    - name: Create SSH Key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pem
    
    - name: Pull changes from Staging branch
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: |
        sshpass -p ${{secrets.SSH_PASSWORD}} ssh -oStrictHostKeyChecking=no ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOSTNAME}} "cd staging/wp-content/plugins/dxl-api && git pull origin staging"

    - name: Pull changes from Master branch
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        sshpass -p ${{secrets.SSH_PASSWORD}} ssh -oStrictHostKeyChecking=no ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOSTNAME}} "cd public_html/wp-content/plugins/dxl-api && git pull"