name: Deploy to Simply.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
    
    - name: Deploy to Simply.com
      run: |  
        sshpass zpmt5dhg ssh -i ${{secrets.SSH_PRIVATE_KEY}} danishxboxleagu.dk@linux279.unoeuro.com 'cd staging/wp-content/plugins/dxl-api && git pull'